version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4:8.3
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - 15480:80
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    networks:
      - network-rinha-nginx-2024q1

networks:
  network-rinha-nginx-2024q1:
    driver: bridge
    name: rinha-nginx-2024q1
    external: true
